### ISSUE TITLE
[C++] Highlight issues with "using" keyword and variables.

### ISSUE THREAD

**Issue by yunkot** [eranif/codelite#1251]
C++11 and newer code that uses "using" keyword for type alias is not highlighted, for instance:
![codelite hightlight issues 06](https://cloud.githubusercontent.com/assets/14065837/14752909/894dec6e-0897-11e6-9cfb-8556293b547b.png)

Note that "typedef" declaration on image above gets properly highlighted, whereas "using" is not.

Also, function parameters seem to be colored inconsistently. This is probably similar to issue  #1077. For example:
![codelite highlight issue 07](https://cloud.githubusercontent.com/assets/14065837/14753025/286b18ee-0898-11e6-8ca2-b06edee1666a.png)
On image above, note that each "Color", "Gray" and "Alpha" function parameters have their unique color. IMHO, all three should be blue similar to local parameters.

**Comment by eranif** [comment]
For the latter (inconsistent coloring) there is probably a class named `Color` somewhere in the workspace, so CodeLite coloured it in green

**Comment by yunkot** [comment]
No, "Color" is not declared anywhere as a data type. In fact, searching for "Color" in header only finds functions which has "Color" as parameter. I tried declaring something like (which doesn't compile, of course): "Color test" and then right-clicking on "Color" to "Find declaration" - it does nothing.

The following headers are used (all of which are just from stdc++):
```cpp
#include <cstdint>
#include <cstdbool>
#include <ctgmath>
#include <limits>
#include <type_traits>
#include <algorithm>
#include <exception>
```
In a new console C++ project, this is how function gets colored:
![codelite highlight issues 08](https://cloud.githubusercontent.com/assets/14065837/14754235/c18850f8-089f-11e6-9a4f-7548f1d69a57.png)

Maybe "Color" data type is pulled off from somewhere by syntax highlighter or even hard-coded?

**Comment by eranif** [comment]
Nothing is hard coded, it is pulled from somewhere...

**Comment by yunkot** [comment]
I still haven't been able to find why CodeLite highlighter recognizes "Color" as some valid data type. Perhaps it finds declaration somewhere (other than stdc++, that's for sure), doesn't take scoping into account and continues to accumulate data types? For instance, this seems to paint "MyInt2" in blue even outside of its scope, when data type no longer exists:
![codelite highlight issues 10](https://cloud.githubusercontent.com/assets/14065837/14756237/6fbbcfbc-08ad-11e6-81f3-d2aed563d8d4.png)

In addition to issue described in first post, C++11 "auto" variables are not painted in any color:
![codelite highlight issue 09](https://cloud.githubusercontent.com/assets/14065837/14756259/98b1de84-08ad-11e6-83b1-ce4d469cac9a.png)

**Comment by yunkot** [comment]
There is one more C+11 highlight issue. "constexpr" constants are not highlighted:

![codelite constexpr highlight issue](https://cloud.githubusercontent.com/assets/14065837/15082236/5a88bc1a-138c-11e6-84c3-74fd7242ca0c.png)

"constexpr" functions are also affected:
![codelite constexpr functions](https://cloud.githubusercontent.com/assets/14065837/15082293/9cf76cf4-138c-11e6-9f6a-fc05e0415290.png)

**Comment by yunkot** [comment]
FYI, C+11 "override" keyword does not appear to be colored - it just appears white. Shouldn't it be purple like "constexpr"?

**Comment by eranif** [comment]
One comment: Please use **text** based examples rather than images - I can't copy them to the clipboard

**Comment by dobragab** [comment]
Hello,

I think the "using" part isn't fixed properly.

Consider this code snippet:

```C++
using Type1 = int;
typedef int Type2;

Type1 t1;
Type2 t2;
```

Type1 and Type2 should be colored same. However, this is not the case, in any of the built-in color themes, as if this "using" wasn't identified as a typedef. For example, this is the result with Monokai_v2.

![screenshot from 2016-09-26 12-47-20](https://cloud.githubusercontent.com/assets/10715919/18831711/8987b52c-83e7-11e6-86f8-55566c484c44.png)

**Comment by yunkot** [comment]
No it doesn't seem to be fixed, at least not in latest weekly build, which claims that it was. In fact, several other issues mentioned here still persist. Relevant code examples, the coloring of which wasn't fixed:
```cpp
using MyInt_Using = int32_t;
MyInt_Using test1 = 5; // test1 not colored properly

auto const startTicks = getTickCount(); // startTicks not colored properly

int32_t constexpr sum(int a, int b) // sum not colored properly
{
  return a + b;
}

struct A
{
  virtual int32_t test() = 0;
}

struct B : public A
{
  int32_t test() override; // override not colored properly
}

{
  typedef uint32_t MyInt3;
}
MyInt3 someInt = 25; // MyInt3 is colored, but since it no longer exists, it shouldn't.
```

**Comment by eranif** [comment]
You are assuming that the syntax highlight is "scope" aware - it is not.
Its just a way of colouring some interesting words in the document. 

```C++
{
  typedef uint32_t MyInt3;
}
MyInt3 someInt = 25; // MyInt3 is colored, but since it no longer exists, it shouldn't.
```

Will always be coloured, since the editor componenets colour words **per document**
It does not contain list of words to colour per position.

**Comment by dobragab** [comment]
Seems like 6a112573aad37521c0c16cd1254e87fab58525c9 solved this, now it looks as intended. Thank you!

**Comment by yunkot** [comment]
Is there any chance to fix "constexpr" and "override" keywords as well?

**Comment by eranif** [comment]
`override` was fixed in commit https://github.com/eranif/codelite/commit/d3112455772c0d3e90a90f7d4cf3dc3853672d2e and f1ea963f4e81930e6ae11c394e529415e2707d4d I was not aware of `constexpr` not working ...
Will check this as well.

**Comment by yunkot** [comment]
Thanks, regarding "constexpr" - variables do seem to be working now in latest weekly build, but functions are still not colored - please see my earlier comment with constexpr "sum" function example.

**Comment by yunkot** [comment]
I have installed weekly build on Windows dated Sep 27, 2016, and coloring seem to be different.
```
// MyNum appears as white
#define MyNum 25 

enum class MyEnum : uint8_t
{
  One, // "One" and "Two" now appear white
  Two
};

void test() // "test" appears white
{
}
```
Above, all aforementioned symbols now appear white, as identifiers. Previously enum constants and defines were green, while function names were blue. Is this supposed to be like that?

**Comment by elch10** [comment]
Here, the local variable count, somehow defined as global. And when I'm using the count function from the STL, it is defined as a variable. This is evident as the present of printf, it is different from the count of the STL.
![noname](https://cloud.githubusercontent.com/assets/15147137/20461015/e860b46a-af05-11e6-88b7-90504f888f4d.png)
