### ISSUE TITLE
completion of *.php5 contents

### ISSUE THREAD

**Issue by wommel** [eranif/codelite#1331]
Now completion and "Goto definition" of *.php5 file contents works for code from within the file itself and its ancestors.

But code from other (not direcly related) *.php5 files in the same project is still not offered and the "Goto definition" function for manualy written code is still not working.

Also when creating new projects *.php5 files are not automaticaly recognized as "Project file types" (no actual problem but maybe there is as relation).

**Comment by eranif** [comment]
I have committed a fix that you can test without building CodeLite.
In your project settings (right click on the blue folder icon in the tree view) ->General->view
Add the extension `*.php5`

To refresh the file view:
After you added it, click on the project->`sync project with file system`

Reparse the workspace:
Workspace->Parse workspace

**Comment by wommel** [comment]
Although new Projects do now automaticaly recognize *.php5 files this sadly did not fix the completion/goto issue regardless of any building, syncing or reparsing.

**Comment by eranif** [comment]
Please provide a small workspace with an example of how to reproduce the problem 
Please include a full detailed steps to reproduce + **expected** result

**Comment by wommel** [comment]
Turns out the problem is a bit more sophisticated than i first claimed:
code from within php5 files is offered for completion only if the file has been saved by codelite once.

[test.zip](https://github.com/eranif/codelite/files/346436/test.zip)

The files and classes Test2 and Test3 are (except for the name and ending) exacly the same.
In Test1 there is an new Object createt from each of them but the completing their attributes only works for Test2 (which is just *.php) until you change something (just some comment or whitespace) in Test3 and save it. From there on completion will work for both.

So this problem only occures if one uses existing code. But why would one have .php5 file endings in an completely new project anyway?^^

**Comment by eranif** [comment]
Looks like the parser thread used some hard code values (only files with the extension `.php`, `.inc` and `.phtml` were considered as PHP files)

It is now using the same set of extensions as the rest of the code. I tested this with the sample workspace you attached and it is not working.

For your case: I guess that you should run 'Workspace->Parse Workspace - Incremental" once and it will fix this

For new projects, it will work out of the box

**Comment by wommel** [comment]
fixed

thanks a lot :)
