### ISSUE TITLE
Type-hint should be taken from the function definition

### ISSUE THREAD

**Issue by sgchris** [eranif/codelite#1750]
![image](https://user-images.githubusercontent.com/475849/30247295-8cf9d560-9619-11e7-94e1-53826d429b6f.png)

\* When changeing the PHPDOC to the correct value, the completion works

**Comment by pattisahusiwa** [comment]
Please don't add this feature before #1708 is fixed. Currently, we don't have a workaround to ignore the bug besides add phpdoc to point the correct value.

**Comment by eranif** [comment]
@pattisahusiwa #1708  should be fixed now

**Comment by pattisahusiwa** [comment]
Still have the issue. Test this

````php
<?php

namespace test;

class PDO
{
    public $varA;
    public $varB;
}

class ClassA
{
    public function Test1(\PDO $a)
    {
    }

    public function Test2(PDO $b)
    {
    }
}
````
Both variable `$a` and `$b` point to `\PDO`. The correct values are `$a` point to `\PDO` and `$b` point to `\test\PDO`.
