### ISSUE TITLE
Copy from LLDB Watch is not working

### ISSUE THREAD

**Issue by mtangoo** [eranif/codelite#2228]
1. Put a Break Point and run app under CL debugger
2. At breakpoint variables are visible under Debugger Window
3. Right Click and copy to clipboard
4. Open Editor and Paste it 
5. Nothing is pasted (or old clipboard contents)

**Comment by eranif** [comment]
Fixed

**Comment by mtangoo** [comment]
using #0eb2e9d1a002609b5740394bd6746da10f559805 it is still not working
