### ISSUE TITLE
high cpu load

### ISSUE THREAD

**Issue by sss123next** [eranif/codelite#2591]
[codelite_profile_2.svg.gz](https://github.com/eranif/codelite/files/5341954/codelite_profile_2.svg.gz)

look at call graph for details

probably related to #2561

* problem confirmed on freebsd and linux

**Comment by sss123next** [comment]
more profiling data

[codelite_profile_1_2.svg.gz](https://github.com/eranif/codelite/files/5348316/codelite_profile_1_2.svg.gz)
[codelite_profile_1_2.txt.gz](https://github.com/eranif/codelite/files/5348318/codelite_profile_1_2.txt.gz)
[codelite_profile_1_2_stacks.txt.gz](https://github.com/eranif/codelite/files/5348319/codelite_profile_1_2_stacks.txt.gz)
[codelite_profile_2_2.svg.gz](https://github.com/eranif/codelite/files/5348320/codelite_profile_2_2.svg.gz)
[codelite_profile_2_2.txt.gz](https://github.com/eranif/codelite/files/5348322/codelite_profile_2_2.txt.gz)
[codelite_profile_2_2_stacks.txt.gz](https://github.com/eranif/codelite/files/5348323/codelite_profile_2_2_stacks.txt.gz)

**Comment by sss123next** [comment]
doing further investigation suggested by one of colleagues i found source of problem, it's incorrect symlink handling,
problem caused byt symlink linke this:

```
ls -la |grep libexec
lrwxrwxrwx    1 sss  sss     1 Oct  7 10:34 libexec -> .
```

note what wxgtk builds built on gtk2 correctly handling this kind of symlinks (tested on same project)

**Comment by sss123next** [comment]
looks like here is also another problem which causing high cpu load, after eliminating a lot of symlink related stuff from trace, here is left following:
```
poll({ 3/POLLIN 4/POLLIN },2,0)			 = 0 (0x0)
recvmsg(3,0x7fffffffe340,0)			 ERR#35 'Resource temporarily unavailable'
recvmsg(3,0x7fffffffe360,0)			 ERR#35 'Resource temporarily unavailable'
poll({ 3/POLLIN 4/POLLIN },2,0)			 = 0 (0x0)
nanosleep({ 0.050000000 })			 = 0 (0x0)
wait4(-1,{ EXITED,val=0 },WNOHANG,0x0)		 = 0 (0x0)
recvmsg(3,0x7fffffffe340,0)			 ERR#35 'Resource temporarily unavailable'
recvmsg(3,0x7fffffffe360,0)			 ERR#35 'Resource temporarily unavailable'
poll({ 3/POLLIN 4/POLLIN },2,0)			 = 0 (0x0)
_umtx_op(0x807f88128,UMTX_OP_WAIT_UINT_PRIVATE,0x0,0x18,0x7fffde7f1a78) ERR#60 'Operation timed out'
_umtx_op(0x807f88158,UMTX_OP_WAIT_UINT_PRIVATE,0x0,0x18,0x7fffde3efa78) ERR#60 'Operation timed out'
_umtx_op(0x804a28b00,UMTX_OP_MUTEX_WAKE2,0x0,0x0,0x0) = 0 (0x0)
_umtx_op(0x804a28b00,UMTX_OP_MUTEX_WAIT,0x0,0x0,0x0) = 0 (0x0)
recvmsg(3,0x7fffffffe340,0)			 ERR#35 'Resource temporarily unavailable'
recvmsg(3,0x7fffffffe360,0)			 ERR#35 'Resource temporarily unavailable'
poll({ 3/POLLIN 4/POLLIN },2,0)			 = 0 (0x0)
recvmsg(3,0x7fffffffe340,0)			 ERR#35 'Resource temporarily unavailable'
recvmsg(3,0x7fffffffe360,0)			 ERR#35 'Resource temporarily unavailable'
poll({ 3/POLLIN 4/POLLIN },2,0)			 = 0 (0x0)
recvmsg(3,0x7fffffffe340,0)			 ERR#35 'Resource temporarily unavailable'
recvmsg(3,0x7fffffffe360,0)			 ERR#35 'Resource temporarily unavailable'
_umtx_op(0x807f880f8,UMTX_OP_WAIT_UINT_PRIVATE,0x0,0x18,0x7fffdebf3a78) ERR#60 'Operation timed out'
poll({ 3/POLLIN 4/POLLIN },2,0)			 = 0 (0x0)
recvmsg(3,0x7fffffffe340,0)			 ERR#35 'Resource temporarily unavailable'
recvmsg(3,0x7fffffffe360,0)			 ERR#35 'Resource temporarily unavailable'
poll({ 3/POLLIN 4/POLLIN },2,0)			 = 0 (0x0)
recvmsg(3,0x7fffffffe490,0)			 ERR#35 'Resource temporarily unavailable'
recvmsg(3,0x7fffffffe4b0,0)			 ERR#35 'Resource temporarily unavailable'
poll({ 3/POLLIN 4/POLLIN },2,0)			 = 0 (0x0)
recvmsg(3,0x7fffffffe490,0)			 ERR#35 'Resource temporarily unavailable'
recvmsg(3,0x7fffffffe4b0,0)			 ERR#35 'Resource temporarily unavailable'
poll({ 3/POLLIN 4/POLLIN },2,0)			 = 0 (0x0)
recvmsg(3,0x7fffffffe340,0)			 ERR#35 'Resource temporarily unavailable'
recvmsg(3,0x7fffffffe360,0)			 ERR#35 'Resource temporarily unavailable'
poll({ 3/POLLIN 4/POLLIN },2,0)			 = 0 (0x0)
_umtx_op(0x807f880e0,UMTX_OP_WAIT_UINT_PRIVATE,0x0,0x18,0x7fffdedf4a78) ERR#60 'Operation timed out'
recvmsg(3,0x7fffffffe340,0)			 ERR#35 'Resource temporarily unavailable'
recvmsg(3,0x7fffffffe360,0)			 ERR#35 'Resource temporarily unavailable'
poll({ 3/POLLIN 4/POLLIN },2,0)			 = 0 (0x0)
recvmsg(3,0x7fffffffe340,0)			 ERR#35 'Resource temporarily unavailable'
recvmsg(3,0x7fffffffe360,0)			 ERR#35 'Resource temporarily unavailable'
poll({ 3/POLLIN 4/POLLIN },2,0)			 = 0 (0x0)
recvmsg(3,0x7fffffffe340,0)			 ERR#35 'Resource temporarily unavailable'
recvmsg(3,0x7fffffffe360,0)			 ERR#35 'Resource temporarily unavailable'
poll({ 3/POLLIN 4/POLLIN },2,0)			 = 0 (0x0)
_umtx_op(0x807f88140,UMTX_OP_WAIT_UINT_PRIVATE,0x0,0x18,0x7fffde5f0a78) ERR#60 'Operation timed out'
recvmsg(3,0x7fffffffe340,0)			 ERR#35 'Resource temporarily unavailable'
recvmsg(3,0x7fffffffe360,0)			 ERR#35 'Resource temporarily unavailable'
select(13,{ 12 },0x0,0x0,{ 0.050000 })		 = 0 (0x0)
poll({ 3/POLLIN 4/POLLIN },2,0)			 = 0 (0x0)
recvmsg(3,0x7fffffffe340,0)			 ERR#35 'Resource temporarily unavailable'
recvmsg(3,0x7fffffffe360,0)			 ERR#35 'Resource temporarily unavailable'
poll({ 3/POLLIN 4/POLLIN },2,0)			 = 0 (0x0)
recvmsg(3,0x7fffffffe340,0)			 ERR#35 'Resource temporarily unavailable'
recvmsg(3,0x7fffffffe360,0)			 ERR#35 'Resource temporarily unavailable'
poll({ 3/POLLIN 4/POLLIN },2,0)			 = 0 (0x0)
recvmsg(3,0x7fffffffe340,0)			 ERR#35 'Resource temporarily unavailable'
recvmsg(3,0x7fffffffe360,0)			 ERR#35 'Resource temporarily unavailable'
poll({ 3/POLLIN 4/POLLIN },2,0)			 = 0 (0x0)
recvmsg(3,0x7fffffffe340,0)			 ERR#35 'Resource temporarily unavailable'
recvmsg(3,0x7fffffffe360,0)			 ERR#35 'Resource temporarily unavailable'
poll({ 3/POLLIN 4/POLLIN },2,0)			 = 0 (0x0)
recvmsg(3,0x7fffffffe340,0)			 ERR#35 'Resource temporarily unavailable'
recvmsg(3,0x7fffffffe360,0)			 ERR#35 'Resource temporarily unavailable'
poll({ 3/POLLIN 4/POLLIN },2,0)			 = 0 (0x0)
recvmsg(3,0x7fffffffe340,0)			 ERR#35 'Resource temporarily unavailable'
recvmsg(3,0x7fffffffe360,0)			 ERR#35 'Resource temporarily unavailable'
_umtx_op(0x807f88068,UMTX_OP_WAIT_UINT_PRIVATE,0x0,0x18,0x7fffdf7f94a8) ERR#60 'Operation timed out'
_umtx_op(0x807f88110,UMTX_OP_WAIT_UINT_PRIVATE,0x0,0x18,0x7fffde9f2a78) ERR#60 'Operation timed out'
nanosleep({ 0.050000000 })			 = 0 (0x0)
poll({ 3/POLLIN 4/POLLIN },2,0)			 = 0 (0x0)
wait4(-1,{ EXITED,val=0 },WNOHANG,0x0)		 = 0 (0x0)
recvmsg(3,0x7fffffffe340,0)			 ERR#35 'Resource temporarily unavailable'
recvmsg(3,0x7fffffffe360,0)			 ERR#35 'Resource temporarily unavailable'
poll({ 3/POLLIN 4/POLLIN },2,0)			 = 0 (0x0)
recvmsg(3,0x7fffffffe340,0)			 ERR#35 'Resource temporarily unavailable'
recvmsg(3,0x7fffffffe360,0)			 ERR#35 'Resource temporarily unavailable'
poll({ 3/POLLIN 4/POLLIN },2,0)			 = 0 (0x0)
_umtx_op(0x807f88158,UMTX_OP_WAIT_UINT_PRIVATE,0x0,0x18,0x7fffde3efa78) ERR#60 'Operation timed out'
_umtx_op(0x807f88128,UMTX_OP_WAIT_UINT_PRIVATE,0x0,0x18,0x7fffde7f1a78) ERR#60 'Operation timed out'
_umtx_op(0x804a28b00,UMTX_OP_MUTEX_WAKE2,0x0,0x0,0x0) = 0 (0x0)
_umtx_op(0x804a28b00,UMTX_OP_MUTEX_WAIT,0x0,0x0,0x0) = 0 (0x0)
recvmsg(3,0x7fffffffe340,0)			 ERR#35 'Resource temporarily unavailable'
recvmsg(3,0x7fffffffe360,0)			 ERR#35 'Resource temporarily unavailable'
poll({ 3/POLLIN 4/POLLIN },2,0)			 = 0 (0x0)
recvmsg(3,0x7fffffffe340,0)			 ERR#35 'Resource temporarily unavailable'
recvmsg(3,0x7fffffffe360,0)			 ERR#35 'Resource temporarily unavailable'
poll({ 3/POLLIN 4/POLLIN },2,0)			 = 0 (0x0)
recvmsg(3,0x7fffffffe340,0)			 ERR#35 'Resource temporarily unavailable'
recvmsg(3,0x7fffffffe360,0)			 ERR#35 'Resource temporarily unavailable'
_umtx_op(0x807f880f8,UMTX_OP_WAIT_UINT_PRIVATE,0x0,0x18,0x7fffdebf3a78) ERR#60 'Operation timed out'
poll({ 3/POLLIN 4/POLLIN },2,0)			 = 0 (0x0)
recvmsg(3,0x7fffffffe340,0)			 ERR#35 'Resource temporarily unavailable'
recvmsg(3,0x7fffffffe360,0)			 ERR#35 'Resource temporarily unavailable'
poll({ 3/POLLIN 4/POLLIN },2,0)			 = 0 (0x0)
recvmsg(3,0x7fffffffe340,0)			 ERR#35 'Resource temporarily unavailable'
recvmsg(3,0x7fffffffe360,0)			 ERR#35 'Resource temporarily unavailable'
poll({ 3/POLLIN 4/POLLIN },2,0)			 = 0 (0x0)
recvmsg(3,0x7fffffffe490,0)			 ERR#35 'Resource temporarily unavailable'
recvmsg(3,0x7fffffffe4b0,0)			 ERR#35 'Resource temporarily unavailable'
poll({ 3/POLLIN 4/POLLIN },2,0)			 = 0 (0x0)
recvmsg(3,0x7fffffffe490,0)			 ERR#35 'Resource temporarily unavailable'
recvmsg(3,0x7fffffffe4b0,0)			 ERR#35 'Resource temporarily unavailable'
poll({ 3/POLLIN 4/POLLIN },2,0)			 = 0 (0x0)
_umtx_op(0x807f880e0,UMTX_OP_WAIT_UINT_PRIVATE,0x0,0x18,0x7fffdedf4a78) ERR#60 'Operation timed out'
recvmsg(3,0x7fffffffe340,0)			 ERR#35 'Resource temporarily unavailable'
recvmsg(3,0x7fffffffe360,0)			 ERR#35 'Resource temporarily unavailable'
poll({ 3/POLLIN 4/POLLIN },2,0)			 = 0 (0x0)
recvmsg(3,0x7fffffffe340,0)			 ERR#35 'Resource temporarily unavailable'
recvmsg(3,0x7fffffffe360,0)			 ERR#35 'Resource temporarily unavailable'
select(13,{ 12 },0x0,0x0,{ 0.050000 })		 = 0 (0x0)
poll({ 3/POLLIN 4/POLLIN },2,0)			 = 0 (0x0)
recvmsg(3,0x7fffffffe340,0)			 ERR#35 'Resource temporarily unavailable'
recvmsg(3,0x7fffffffe360,0)			 ERR#35 'Resource temporarily unavailable'
_umtx_op(0x807f88140,UMTX_OP_WAIT_UINT_PRIVATE,0x0,0x18,0x7fffde5f0a78) ERR#60 'Operation timed out'
poll({ 3/POLLIN 4/POLLIN },2,0)			 = 0 (0x0)
recvmsg(3,0x7fffffffe340,0)			 ERR#35 'Resource temporarily unavailable'
recvmsg(3,0x7fffffffe360,0)			 ERR#35 'Resource temporarily unavailable'
poll({ 3/POLLIN 4/POLLIN },2,0)			 = 0 (0x0)
recvmsg(3,0x7fffffffe340,0)			 ERR#35 'Resource temporarily unavailable'
recvmsg(3,0x7fffffffe360,0)			 ERR#35 'Resource temporarily unavailable'
poll({ 3/POLLIN 4/POLLIN },2,0)			 = 0 (0x0)
recvmsg(3,0x7fffffffe340,0)			 ERR#35 'Resource temporarily unavailable'
recvmsg(3,0x7fffffffe360,0)			 ERR#35 'Resource temporarily unavailable'
poll({ 3/POLLIN 4/POLLIN },2,0)			 = 0 (0x0)
recvmsg(3,0x7fffffffe340,0)			 ERR#35 'Resource temporarily unavailable'
recvmsg(3,0x7fffffffe360,0)			 ERR#35 'Resource temporarily unavailable'
poll({ 3/POLLIN 4/POLLIN },2,0)			 = 0 (0x0)
nanosleep({ 0.050000000 })			 = 0 (0x0)
wait4(-1,{ EXITED,val=0 },WNOHANG,0x0)		 = 0 (0x0)
recvmsg(3,0x7fffffffe340,0)			 ERR#35 'Resource temporarily unavailable'
recvmsg(3,0x7fffffffe360,0)			 ERR#35 'Resource temporarily unavailable'
poll({ 3/POLLIN 4/POLLIN },2,0)			 = 0 (0x0)
_umtx_op(0x807f88068,UMTX_OP_WAIT_UINT_PRIVATE,0x0,0x18,0x7fffdf7f94a8) ERR#60 'Operation timed out'
_umtx_op(0x807f88110,UMTX_OP_WAIT_UINT_PRIVATE,0x0,0x18,0x7fffde9f2a78) ERR#60 'Operation timed out'
recvmsg(3,0x7fffffffe340,0)			 ERR#35 'Resource temporarily unavailable'
recvmsg(3,0x7fffffffe360,0)			 ERR#35 'Resource temporarily unavailable'
poll({ 3/POLLIN 4/POLLIN },2,0)			 = 0 (0x0)
recvmsg(3,0x7fffffffe340,0)			 ERR#35 'Resource temporarily unavailable'
recvmsg(3,0x7fffffffe360,0)			 ERR#35 'Resource temporarily unavailable'
poll({ 3/POLLIN 4/POLLIN },2,0)			 = 0 (0x0)
recvmsg(3,0x7fffffffe490,0)			 ERR#35 'Resource temporarily unavailable'
recvmsg(3,0x7fffffffe4b0,0)			 ERR#35 'Resource temporarily unavailable'
poll({ 3/POLLIN 4/POLLIN },2,0)			 = 0 (0x0)
recvmsg(3,0x7fffffffe490,0)			 ERR#35 'Resource temporarily unavailable'
recvmsg(3,0x7fffffffe4b0,0)			 ERR#35 'Resource temporarily unavailable'
poll({ 3/POLLIN 4/POLLIN },2,0)			 = 0 (0x0)
_umtx_op(0x807f88128,UMTX_OP_WAIT_UINT_PRIVATE,0x0,0x18,0x7fffde7f1a78) ERR#60 'Operation timed out'
_umtx_op(0x807f88158,UMTX_OP_WAIT_UINT_PRIVATE,0x0,0x18,0x7fffde3efa78) ERR#60 'Operation timed out'
_umtx_op(0x804a28b00,UMTX_OP_MUTEX_WAIT,0x0,0x0,0x0) = 0 (0x0)
recvmsg(3,0x7fffffffe340,0)			 ERR#35 'Resource temporarily unavailable'
recvmsg(3,0x7fffffffe360,0)			 ERR#35 'Resource temporarily unavailable'
poll({ 3/POLLIN 4/POLLIN },2,0)			 = 0 (0x0)
recvmsg(3,0x7fffffffe340,0)			 ERR#35 'Resource temporarily unavailable'
recvmsg(3,0x7fffffffe360,0)			 ERR#35 'Resource temporarily unavailable'
poll({ 3/POLLIN 4/POLLIN },2,0)			 = 0 (0x0)
recvmsg(3,0x7fffffffe340,0)			 ERR#35 'Resource temporarily unavailable'
recvmsg(3,0x7fffffffe360,0)			 ERR#35 'Resource temporarily unavailable'
_umtx_op(0x807f880f8,UMTX_OP_WAIT_UINT_PRIVATE,0x0,0x18,0x7fffdebf3a78) ERR#60 'Operation timed out'
poll({ 3/POLLIN 4/POLLIN },2,0)			 = 0 (0x0)
recvmsg(3,0x7fffffffe340,0)			 ERR#35 'Resource temporarily unavailable'
recvmsg(3,0x7fffffffe360,0)			 ERR#35 'Resource temporarily unavailable'
poll({ 3/POLLIN 4/POLLIN },2,0)			 = 0 (0x0)
recvmsg(3,0x7fffffffe340,0)			 ERR#35 'Resource temporarily unavailable'
recvmsg(3,0x7fffffffe360,0)			 ERR#35 'Resource temporarily unavailable'
poll({ 3/POLLIN 4/POLLIN },2,0)			 = 0 (0x0)
recvmsg(3,0x7fffffffe340,0)			 ERR#35 'Resource temporarily unavailable'
recvmsg(3,0x7fffffffe360,0)			 ERR#35 'Resource temporarily unavailable'
_umtx_op(0x807f880e0,UMTX_OP_WAIT_UINT_PRIVATE,0x0,0x18,0x7fffdedf4a78) ERR#60 'Operation timed out'
select(13,{ 12 },0x0,0x0,{ 0.050000 })		 = 0 (0x0)
poll({ 3/POLLIN 4/POLLIN },2,0)			 = 0 (0x0)
recvmsg(3,0x7fffffffe340,0)			 ERR#35 'Resource temporarily unavailable'
recvmsg(3,0x7fffffffe360,0)			 ERR#35 'Resource temporarily unavailable'
poll({ 3/POLLIN 4/POLLIN },2,0)			 = 0 (0x0)
recvmsg(3,0x7fffffffe340,0)			 ERR#35 'Resource temporarily unavailable'
recvmsg(3,0x7fffffffe360,0)			 ERR#35 'Resource temporarily unavailable'
poll({ 3/POLLIN 4/POLLIN },2,0)			 = 0 (0x0)
recvmsg(3,0x7fffffffe340,0)			 ERR#35 'Resource temporarily unavailable'
recvmsg(3,0x7fffffffe360,0)			 ERR#35 'Resource temporarily unavailable'
_umtx_op(0x807f88140,UMTX_OP_WAIT_UINT_PRIVATE,0x0,0x18,0x7fffde5f0a78) ERR#60 'Operation timed out'
poll({ 3/POLLIN 4/POLLIN },2,0)			 = 0 (0x0)
recvmsg(3,0x7fffffffe340,0)			 ERR#35 'Resource temporarily unavailable'
recvmsg(3,0x7fffffffe360,0)			 ERR#35 'Resource temporarily unavailable'
poll({ 3/POLLIN 4/POLLIN },2,0)			 = 0 (0x0)
recvmsg(3,0x7fffffffe340,0)			 ERR#35 'Resource temporarily unavailable'
recvmsg(3,0x7fffffffe360,0)			 ERR#35 'Resource temporarily unavailable'
poll({ 3/POLLIN 4/POLLIN },2,0)			 = 0 (0x0)
recvmsg(3,0x7fffffffe340,0)			 ERR#35 'Resource temporarily unavailable'
recvmsg(3,0x7fffffffe360,0)			 ERR#35 'Resource temporarily unavailable'
nanosleep({ 0.050000000 })			 = 0 (0x0)
wait4(-1,{ EXITED,val=0 },WNOHANG,0x0)		 = 0 (0x0)
poll({ 3/POLLIN 4/POLLIN },2,0)			 = 0 (0x0)
recvmsg(3,0x7fffffffe340,0)			 ERR#35 'Resource temporarily unavailable'
recvmsg(3,0x7fffffffe360,0)			 ERR#35 'Resource temporarily unavailable'
poll({ 3/POLLIN 4/POLLIN },2,0)			 = 0 (0x0)
recvmsg(3,0x7fffffffe340,0)			 ERR#35 'Resource temporarily unavailable'
recvmsg(3,0x7fffffffe360,0)			 ERR#35 'Resource temporarily unavailable'
poll({ 3/POLLIN 4/POLLIN },2,0)			 = 0 (0x0)
_umtx_op(0x807f88068,UMTX_OP_WAIT_UINT_PRIVATE,0x0,0x18,0x7fffdf7f94a8) ERR#60 'Operation timed out'
recvmsg(3,0x7fffffffe340,0)			 ERR#35 'Resource temporarily unavailable'
recvmsg(3,0x7fffffffe360,0)			 ERR#35 'Resource temporarily unavailable'
_umtx_op(0x807f88110,UMTX_OP_WAIT_UINT_PRIVATE,0x0,0x18,0x7fffde9f2a78) ERR#60 'Operation timed out'
poll({ 3/POLLIN 4/POLLIN },2,0)			 = 0 (0x0)
recvmsg(3,0x7fffffffe340,0)			 ERR#35 'Resource temporarily unavailable'
recvmsg(3,0x7fffffffe360,0)			 ERR#35 'Resource temporarily unavailable'
poll({ 3/POLLIN 4/POLLIN },2,0)			 = 0 (0x0)
recvmsg(3,0x7fffffffe340,0)			 ERR#35 'Resource temporarily unavailable'
recvmsg(3,0x7fffffffe360,0)			 ERR#35 'Resource temporarily unavailable'
poll({ 3/POLLIN 4/POLLIN },2,0)			 = 0 (0x0)
_umtx_op(0x807f88128,UMTX_OP_WAIT_UINT_PRIVATE,0x0,0x18,0x7fffde7f1a78) ERR#60 'Operation timed out'
_umtx_op(0x807f88158,UMTX_OP_WAIT_UINT_PRIVATE,0x0,0x18,0x7fffde3efa78) ERR#60 'Operation timed out'
recvmsg(3,0x7fffffffe340,0)			 ERR#35 'Resource temporarily unavailable'
recvmsg(3,0x7fffffffe360,0)			 ERR#35 'Resource temporarily unavailable'
poll({ 3/POLLIN 4/POLLIN },2,0)			 = 0 (0x0)
recvmsg(3,0x7fffffffe490,0)			 ERR#35 'Resource temporarily unavailable'
recvmsg(3,0x7fffffffe4b0,0)			 ERR#35 'Resource temporarily unavailable'
poll({ 3/POLLIN 4/POLLIN },2,0)			 = 0 (0x0)
recvmsg(3,0x7fffffffe490,0)			 ERR#35 'Resource temporarily unavailable'
recvmsg(3,0x7fffffffe4b0,0)			 ERR#35 'Resource temporarily unavailable'
poll({ 3/POLLIN 4/POLLIN },2,0)			 = 0 (0x0)
recvmsg(3,0x7fffffffe340,0)			 ERR#35 'Resource temporarily unavailable'
recvmsg(3,0x7fffffffe360,0)			 ERR#35 'Resource temporarily unavailable'
poll({ 3/POLLIN 4/POLLIN },2,0)			 = 0 (0x0)
_umtx_op(0x807f880f8,UMTX_OP_WAIT_UINT_PRIVATE,0x0,0x18,0x7fffdebf3a78) ERR#60 'Operation timed out'
recvmsg(3,0x7fffffffe340,0)			 ERR#35 'Resource temporarily unavailable'
recvmsg(3,0x7fffffffe360,0)			 ERR#35 'Resource temporarily unavailable'
poll({ 3/POLLIN 4/POLLIN },2,0)			 = 0 (0x0)
recvmsg(3,0x7fffffffe340,0)			 ERR#35 'Resource temporarily unavailable'
recvmsg(3,0x7fffffffe360,0)			 ERR#35 'Resource temporarily unavailable'
poll({ 3/POLLIN 4/POLLIN },2,0)			 = 0 (0x0)
select(13,{ 12 },0x0,0x0,{ 0.050000 })		 = 0 (0x0)
_umtx_op(0x807f880e0,UMTX_OP_WAIT_UINT_PRIVATE,0x0,0x18,0x7fffdedf4a78) ERR#60 'Operation timed out'
recvmsg(3,0x7fffffffe340,0)			 ERR#35 'Resource temporarily unavailable'
recvmsg(3,0x7fffffffe360,0)			 ERR#35 'Resource temporarily unavailable'
poll({ 3/POLLIN 4/POLLIN },2,0)			 = 0 (0x0)
recvmsg(3,0x7fffffffe340,0)			 ERR#35 'Resource temporarily unavailable'
recvmsg(3,0x7fffffffe360,0)			 ERR#35 'Resource temporarily unavailable'
poll({ 3/POLLIN 4/POLLIN },2,0)			 = 0 (0x0)
recvmsg(3,0x7fffffffe340,0)			 ERR#35 'Resource temporarily unavailable'
recvmsg(3,0x7fffffffe360,0)			 ERR#35 'Resource temporarily unavailable'
poll({ 3/POLLIN 4/POLLIN },2,0)			 = 0 (0x0)
recvmsg(3,0x7fffffffe340,0)			 ERR#35 'Resource temporarily unavailable'
recvmsg(3,0x7fffffffe360,0)			 ERR#35 'Resource temporarily unavailable'
poll({ 3/POLLIN 4/POLLIN },2,0)			 = 0 (0x0)
```

a lot of this, like 100mb per minute, probably incorrect `poll` timeout is set.

**Comment by dghart** [comment]
Hi,

>Problem confirmed on freebsd and linux

Which linux distro/version? I've not noticed the problem on recent debian/ubuntu/fedora/suse releases; though admittedly I'm using a desktop box with multiple cores.

>ls -la |grep libexec

Is that just an _example_ of bad symlinking, or do you mean specifically libexec? Does CodeLite do this?

Similarly, I can't see anything specific to CodeLite in your call-graphs or trace. IIUC (which is certainly not guaranteed!) there are wxWidgets calls and system calls, though it's also suspicious that you see the problem only with GTK+3 builds of wxWidgets.
Can you reproduce the problem in one of the samples that come with the wxWidgets source code? If so, I suggest you report the problem [there](https://trac.wxwidgets.org/).

What (if anything) do you suggest can be done at CodeLite level?

Regards,

David

**Comment by sss123next** [comment]
> Which linux distro/version? I've not noticed the problem on recent debian/ubuntu/fedora/suse releases; though admittedly I'm using a desktop box with multiple cores.

tested on current exherbo linux and current freebsd

> 
> > ls -la |grep libexec
> 
> Is that just an _example_ of bad symlinking, or do you mean specifically libexec? Does CodeLite do this?

it's just an example, it is not necessary should be named `libexec`



> Similarly, I can't see anything specific to CodeLite in your call-graphs or trace. IIUC (which is certainly not guaranteed!) there are wxWidgets calls and system calls, though it's also suspicious that you see the problem only with GTK+3 builds of wxWidgets.


yes, i do not see  codelite calls also, maybe some incorrect call to wxwidgets/gtk causing infinite recursion or something like this

> Can you reproduce the problem in one of the samples that come with the wxWidgets source code? If so, I suggest you report the problem [there](https://trac.wxwidgets.org/).

this is possible wxwigets or gtk problem, yes.

> What (if anything) do you suggest can be done at CodeLite level?

for now i want to track problem and gather info.

**Comment by eranif** [comment]
Can you disable the Language Server plugin?

**Comment by sss123next** [comment]
it is disabled from the beginning, not related.
also it;s is possible to enter this bad state also  on wxgtk3+ gtk2, but harder, so it is not gtk3 specific, probably some race condition which just easier to trigger on gtk3 builds

i am observed some "behavior pattern":

most often problem occurs after "build->build workspace" call from workspace menu (right mouse click on workspace root item).
bad state will be infinite, but can be reset by opening new source files in editor or closing already opened - this works on freebsd and does not on linux, on linux opening some dialogs (Manage Plugins...) for example resetting this infinite bad state.

also looking on stack in this bad state maybe provide some more clue.

[gdb.txt](https://github.com/eranif/codelite/files/5360463/gdb.txt)  - stack from linux

**Comment by sss123next** [comment]
i can also create stack with debug builds if required, looks like some gtk internals missing here.

**Comment by rozhuk-im** [comment]
This produced by code:
```
void* ZombieReaperPOSIX::Entry()
{
    while ( !TestDestroy() ) {
        int status (0);
        pid_t pid = ::waitpid((pid_t)-1, &status, WNOHANG);
        if ( pid > 0 ) {
            // Notify about this process termination
            wxProcessEvent event(0, pid, status);
            event.SetEventType( wxEVT_CL_PROCESS_TERMINATED );
            EventNotifier::Get()->AddPendingEvent( event );
            CL_DEBUG("ZombieReaperPOSIX: process %d exited with status code %d", (int)pid, status);
        }
        wxThread::Sleep(50);
    }
    
    CL_DEBUG("ZombieReaperPOSIX: going down");
    return NULL;
}
```

```
  thread #17, name = 'codelite'
    frame #0: 0x00000008037f3bca libc.so.7`__sys_nanosleep + 10
    frame #1: 0x0000000803691a5c libthr.so.3`___lldb_unnamed_symbol36$$libthr.so.3 + 44
    frame #2: 0x00000008027d0286 libwx_baseu-3.1.so.4`wxMilliSleep(unsigned long) + 86
    frame #3: 0x000000080331e3fa liblibcodelite.so`ZombieReaperPOSIX::Entry() + 234
    frame #4: 0x00000008027c8142 libwx_baseu-3.1.so.4`wxThread::CallEntry() + 18
    frame #5: 0x00000008027c7c5c libwx_baseu-3.1.so.4`___lldb_unnamed_symbol1432$$libwx_baseu-3.1.so.4 + 1884
    frame #6: 0x000000080368f052 libthr.so.3`___lldb_unnamed_symbol1$$libthr.so.3 + 354
```

```
36881: nanosleep({ 0.050000000 })		 = 0 (0x0)
36881: wait4(-1,{ EXITED,val=0 },WNOHANG,0x0)	 = 0 (0x0)
36881: _umtx_op(0x80b110158,UMTX_OP_WAIT_UINT_PRIVATE,0x0,0x18,0x7fffde3eea98) ERR#60 'Operation timed out'
36881: poll({ 3/POLLIN 4/POLLIN 6/POLLIN 21/POLLIN|POLLPRI },4,0) = 0 (0x0)
36881: _umtx_op(0x80b110098,UMTX_OP_WAIT_UINT_PRIVATE,0x0,0x18,0x7fffdf3f6528) ERR#60 'Operation timed out'
36881: recvmsg(3,0x7fffffffd4b0,0)		 ERR#35 'Resource temporarily unavailable'
36881: _umtx_op(0x80b110128,UMTX_OP_WAIT_UINT_PRIVATE,0x0,0x18,0x7fffde7f0a98) ERR#60 'Operation timed out'
36881: poll({ 3/POLLIN 4/POLLIN 6/POLLIN 21/POLLIN|POLLPRI },4,0) = 0 (0x0)
36881: _umtx_op(0x80b110170,UMTX_OP_WAIT_UINT_PRIVATE,0x0,0x18,0x7fffde1eda98) ERR#60 'Operation timed out'
36881: _umtx_op(0x80b110188,UMTX_OP_WAIT_UINT_PRIVATE,0x0,0x18,0x7fffddfeca98) ERR#60 'Operation timed out'
36881: select(18,{ 17 },0x0,0x0,{ 0.050000 })	 = 0 (0x0)
36881: recvmsg(3,0x7fffffffd4b0,0)		 ERR#35 'Resource temporarily unavailable'
36881: _umtx_op(0x80b110110,UMTX_OP_WAIT_UINT_PRIVATE,0x0,0x18,0x7fffde9f1a98) ERR#60 'Operation timed out'
36881: _umtx_op(0x80b110140,UMTX_OP_WAIT_UINT_PRIVATE,0x0,0x18,0x7fffde5efa98) ERR#60 'Operation timed out'
36881: poll({ 3/POLLIN 4/POLLIN 6/POLLIN 21/POLLIN|POLLPRI },4,0) = 0 (0x0)
36881: nanosleep({ 0.050000000 })		 = 0 (0x0)
```

**Comment by rozhuk-im** [comment]
@eranif can you increase ```wxThread::Sleep(50);``` to 1 second? Or do not use ```WNOHANG```?

**Comment by rozhuk-im** [comment]
I try patch this, and it did not fix all CPU usage, but I did not see ```nanosleep()``` any more.

Next problem some where in main gui loop.
I have big project and 100% CPU load on one core starts after project build.

If I clear build log or click on error inside or scroll up - it stop eating CPU.
```
./update_python_bindings.sh: swig3.0: not found
*** [PreBuild] Error code 127
```
probably code try to resolve source code string number or something else.

**Comment by sss123next** [comment]
looks like problem does not occurs on latest builds, i will leave this ticket open for now, i will do more tests.

**Comment by eranif** [comment]
fixed

**Comment by sss123next** [comment]
unfortunately problem still here 


![2020-12-24_08-07](https://user-images.githubusercontent.com/202772/103073286-4abe7d00-45bf-11eb-90bf-e7faef58fed9.png)

**Comment by eranif** [comment]
Did you try with GTK3?

**Comment by sss123next** [comment]
not tested yet latest master with gtk3

**Comment by rozhuk-im** [comment]
With GTK3 still require to clear build log or scroll it up to stop 100% usage (on 1 single thread).
