### ISSUE TITLE
Cannot turn off "Show file path on tab label"

### ISSUE THREAD

**Issue by audrius-u** [eranif/codelite#3038]
The checkbox _Settings->Preferences->Tabs->Show file path on tab label_ is ticked. When I untick it and press [OK] - nothing happens, tab labels stay with file path, and upon opening the Preferences window, the checkbox is ticked again. Restart of CodeLite does not help. I could not find this setting in config file(-s), can you give a hint please?

_Settings->Preferences->Tabs->Show close button_ on tabs cannot be unticked as well.  Other settings on the same page work correctly.

CodeLite 16.1.0 - Weekly Build June 2, 2022 on Windows 11

**Comment by eranif** [comment]
Please try CodeLite 16.2
Most of these issues are fixed (I tested the ones you mentioned here, and it works)
Note that I am using Windows 10

**Comment by audrius-u** [comment]
I have just tested latest 16.2.0 on two different machines, both running Windows 11Pro and the problem remains - both abovementioned Tab setting options cannot be turned off. I tried the following:
* kept Codelite settings from 16.1.0 (which are kept from v15 and earlier),
* made a clean install and even removed %APPDATA%\codelite,
* tried with and without workspace opened.

And the problem persists - untick the checkboxes (some or all), click [OK], repoen settings and first two boxes gets checked again. Other settings in Tab group seems to work correctly.

**Comment by eranif** [comment]
It seems to be working fine on Windows 10, macOS monterey and Ubuntu 20.04...
I don't have Windows 11 so can't test it there

However, since I am sure you are experiencing what you are saying, I have re-written the class that stores these options
hopefully, this should work fine now

https://github.com/eranif/codelite/commit/2da8e2ae9a01d76afd46086f956e6ec4402f8c9a
