### ISSUE TITLE
[Bug]: CodeLite points to a warning instead of error, reports incorrect number of errors

### ISSUE THREAD

**Issue by yunkot** [eranif/codelite#3552]
### What happened?

When building a project with CodeLite, it always reports:
> === build completed successfully (0 errors, 0 warnings) ===

regardless of how many errors and warnings are actually there.

A portion of Build output:
> /data1/Dev/TestProject/Projects/CodeLite/IndustrialDemo/IndustrialDemo/main.cpp:2835:42: error: use of undeclared identifier 'f'[0m
>  2835 |     printf("Failed initializing GTK.\n");f
>       |                                          ^
> /bin/clang++  -c  "/data1/Dev/TestProject/framework/src/PXT.PostProcessing.Modern.cpp" -march=haswell -std=gnu++20 -pthread -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/fribidi -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/gtkmm-3.0 -I/usr/lib/x86_64-linux-gnu/gtkmm-3.0/include -I/usr/include/giomm-2.4 -I/usr/lib/x86_64-linux-gnu/giomm-2.4/include -I/usr/include/glibmm-2.4 -I/usr/lib/x86_64-linux-gnu/glibmm-2.4/include -I/usr/include/sigc++-2.0 -I/usr/lib/x86_64-linux-gnu/sigc++-2.0/include -I/usr/include/gtk-3.0 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/x86_64-linux-gnu -I/usr/include/webp -I/usr/include/gio-unix-2.0 -I/usr/include/atk-1.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/cairomm-1.0 -I/usr/lib/x86_64-linux-gnu/cairomm-1.0/include -I/usr/include/pangomm-1.4 -I/usr/lib/x86_64-linux-gnu/pangomm-1.4/include -I/usr/include/atkmm-1.6 -I/usr/lib/x86_64-linux-gnu/atkmm-1.6/include -I/usr/include/gtk-3.0/unix-print -I/usr/include/gdkmm-3.0 -I/usr/lib/x86_64-linux-gnu/gdkmm-3.0/include  -g -O0 -Wall -fsanitize=address -Wno-parentheses -Wno-missing-braces -D__INSTRUCTIONS_AVX2 -D__PXT_DEBUG -D__PXT_FAST_DOUBLE_PARSER -DTestProject_OPENGL_NATIVE  -o /temp/IndustrialDemo/Debug/up_up_up_up_framework_src_PXT.PostProcessing.Modern.cpp.o -I. -I../../../../framework -I../../../../framework/include -I../../../../framework/include/platforms -I../../../../framework/include/providers -I../../../../framework/include/shaders -I../../../../thirdparty/fast_double_parser -I../../../../thirdparty/assimp/include -I.
> 3 warnings and 1 error generated.
> make[1]: *** [IndustrialDemo.mk:250: /temp/IndustrialDemo/Debug/main.cpp.o] Error 1
> make[1]: *** Waiting for unfinished jobs....
> 1 warning generated.
> [38;5;250mmake[1]: Leaving directory '/data1/Dev/TestProject/Projects/CodeLite/IndustrialDemo/IndustrialDemo'[0m
> make: *** [Makefile:5: All] Error 2
> [38;5;160m=== build completed successfully (0 errors, 0 warnings) ===[0m
> 

Also, when there is an error, CodeLite points to some random warning instead of the actual error.
This is a regression since commit bf67d735a8d6784d7c223dcf11c3c47b7fcc2af2, where none of these two issues occur.
I believe this is a showstopper bug as CodeLite is unusable this way.

### Version

Git commit 31fa988e71f9eaac83282cfcbcd132d068fdf85b

### Operating system

Linux Mint 22, Kernel 6.8.0-51-generic, Xorg

**Comment by eranif** [comment]
Can u try the latest master?

**Comment by eranif** [comment]
should fix the first issue

**Comment by yunkot** [comment]
The message "build completed successfully (0 errors, 0 warnings)" has been corrected (as of revision 1517e2e4b28595497330711e0c3634d06f65f61e), but the problem with incorrect error remains.

If a source file has both warning and an error, CodeLite now places cursor at warning, not at error. In "Build Settings" - "Build Panel", I have "Skip Warnings" and "When build completes, scroll to the first error line" selected.

**Comment by eranif** [comment]
are they on the same line? (the error and warning)

**Comment by eranif** [comment]
Please try again 😄

**Comment by yunkot** [comment]
No, there are like 2000 lines between them, you have to scroll *a lot* to find the actual error. Also, it looks like original problem still remains: in another compilation try, CodeLite switches to a completely different file containing a warning of an unused function, instead of pointing to the error.

**Comment by eranif** [comment]
@yunkot  I just committed a fix for the skip-warning issue - please try it

**Comment by yunkot** [comment]
> Please try again 😄

Thanks, trying right now...

**Comment by yunkot** [comment]
The issue appears to be fixed now. Thanks for a quick fix!

**Comment by yunkot** [comment]
I'm using commit a0cdc60aa7c6e86fc28b09622cf736f99e4a8297 from today. Unfortunately, both issues are back. 
CodeLite shows:
"=== build completed successfully (0 errors, 0 warnings) ===" 
regardless of errors and warnings and does not point to error location anymore. 
In fact, now it doesn't point anywhere, the cursor position doesn't change after building.

**Comment by eranif** [comment]
I suspect that this is a new issue. Please provide a reliable way to reproduce this as it now works well for me

**Comment by eranif** [comment]
One thing that comes to mind: do you have a toolchain defined for your workspace? If there is no toolchain defined,  parsing for errors is not done.

<img width="701" alt="Capture" src="https://github.com/user-attachments/assets/f00679b8-edde-43ba-bfef-3e3b9a1a744d" />

**Comment by yunkot** [comment]
The bug description and log output is exactly the same as on top post, but the issue is now sporadic - some projects experience it and some don't. In trivial new project it doesn't happen, but in several big projects it does occur.

For instance, this is Build output from another project:

> make[1]: *** [TestGUI.mk:253: /temp/TestGUI/Debug/main.cpp.o] Error 1
> make[1]: Leaving directory '/data1/Dev/IndustrialFramework/Projects/CodeLite/TestGUI/TestGUI'
> make: *** [Makefile:5: All] Error 2
> === build completed successfully (0 errors, 0 warnings) ===

As for the toolchain, I don't have such option. Here is screenshot of my "Workspace Settings":
![WorkspaceSettings](https://github.com/user-attachments/assets/46191061-bd42-4b44-b40e-b117a471b8f3)
If I create a new C++ workspace, it has the same settings window.

**Comment by eranif** [comment]
Then you are not using a file-system-workspace, but a standard C++ workspace.

**Comment by yunkot** [comment]
Yes I am. Shouldn't I?

**Comment by eranif** [comment]
No, both are fine, I was focusing on the file system workspace fixes, but it should work for both. It's been a while since I used this workspace type. Do you have an example that shows the problem? i.e. a minimal workspace with 1-2 C++ files

**Comment by yunkot** [comment]
I've tried several simple projects and issue doesn't occur there. The issue occurs in about 2/3 of big projects (100+ source and include files) that I'm trying and can't really see what is different between them: all of them are C++ workspaces, where each workspace contains a single C++ project using "Default" Makefile Generator. 

Is there anything else I can do to help debug this?

**Comment by eranif** [comment]
First, From the menu:

`settings -> preferences -> misc`,  change the log level to `Debug`

Next,  in a terminal:

```bash
tail -f ~/.codelite/logs/codelite.log&
```

Build your project.

In the log, you should be able to see lines starting with:
`(Build Tab View)` when you locate these lines, paste here the log (or upload the entire log)

**Comment by yunkot** [comment]
I've built CodeLite for debug and set Log Level to Debug, but I'm only getting this:

```
[13:50:50:584 DBG] [Main] Executing: /home/LocalUser/devel/CLbuild/bin/codelite-make --workspace=/data1/Dev/IndustrialFramework/Projects/CodeLite/IndustrialDemo/IndustrialDemo.workspace --json  --config=Debug --settings=/home/LocalUser/.codelite-dbg/config/build_settings.xml
[13:50:50:716 DBG] Checking paths for changes: [/data1/Dev/IndustrialFramework/Projects/CodeLite/IndustrialDemo/compile_commands.json]
[13:50:50:720 DBG] New checksum is: [ D561A9EFB3E6D8D27D58EAE54CA5945B ]
[13:50:50:720 DBG] Old checksum is: [ D561A9EFB3E6D8D27D58EAE54CA5945B ]
[13:50:50:720 DBG] File: /data1/Dev/IndustrialFramework/Projects/CodeLite/IndustrialDemo/compile_commands.json exists: 1
[13:50:50:720 DBG] No changes detected for paths: [/data1/Dev/IndustrialFramework/Projects/CodeLite/IndustrialDemo/compile_commands.json]
```
Am I missing something?

P.S. (offtopic) This was first run of CodeLite debug build so it didn't have any settings. CodeLite started "maximized" much bigger than the screen and is stuck in this state, I can move it around but can't resize or "unmaximize" it, restarting doesn't help. Do you know how can I "unmaximize" it by editing some settings?

**Comment by eranif** [comment]
Did you try clicking on on error message? does it work?
Also, make sure that: "Settings -> Build settings -> Build panel -> when build completes, scroll to the first error line" is checked

**Comment by eranif** [comment]
Can you post here the complete file?

**Comment by yunkot** [comment]
Clicking on error line in Build panel works only when I click on line with error, e.g. "error: use of undeclared identifier 'f'". Clicking on next line with the message and arrow, where error is, e.g. "SceneMesh* const mesh = object->mesh();f" doesn't go to that line.

"When build completes, scroll to the first error line" is checked. Since this is a debug build, it has "Skip warnings" unchecked and it doesn't jump to any of the warnings either.

I've attached complete log file.
[codelite.log](https://github.com/user-attachments/files/18263930/codelite.log)

**Comment by eranif** [comment]
> Clicking on error line in Build panel works only when I click on line with error, e.g. "error: use of undeclared identifier 'f'". Clicking on next line with the message and arrow, where error is, e.g. "SceneMesh* const mesh = object->mesh();f" doesn't go to that line.

This never worked before - you have to click on lines that has "file:line" in it. We could implement that associates the next errors without line information to the previous one that has file:line information

**Comment by eranif** [comment]
Anyways, I added more log lines so we should be able to get more from the log. If you can update and upload the log file

**Comment by yunkot** [comment]
After updating, I'm still not getting any log output with "(Build Tab View)" prefix. Maybe the code in question never gets to execute?

When I click with mouse in Build output panel on some lines, I do get "(Build Tab View)" log output, e.g.:
```
[17:21:41:220 DBG] [Main] (Build Tab View) Searching for line info for view line: 112
[17:21:41:220 DBG] [Main] (Build Tab View) No line info for view line: 112
[17:21:41:220 DBG] [Main] (Build Tab View) firing hotspot event for:
[17:21:41:220 DBG] [Main] (Build Tab View) file: /data1/Dev/IndustrialFramework/Projects/CodeLite/IndustrialDemo/IndustrialDemo/main.cpp
[17:21:41:221 DBG] [Main] (Build Tab View) line: 2793
[17:21:41:221 DBG] [Main] (Build Tab View) column: 44
[17:21:41:221 DBG] [Main] (Build Tab View) using default open file handler
```

**Comment by eranif** [comment]
Can you please upload the entire log?

**Comment by yunkot** [comment]
Just to clarify: when I open one of the big projects that exhibit this issue and try to build them while having errors/warnings, I experience both of the issues and no "(Build Tab View)" messages. When I open a simpler project that doesn't exhibit these issues and try to build it, it does produce "(Build Tab View)" messages.

**Comment by yunkot** [comment]
I've attached the log when trying to build project that exhibits the issue.
[codelite.log](https://github.com/user-attachments/files/18264306/codelite.log)

**Comment by eranif** [comment]
So I am bit confused. To be clear - "the issue" is?

When build complete, you CodeLite does not open the first error from the build log?

OR:

Clicking on an error message in the log view on a line that has the `<file>:<line>` pattern does not work?

**Comment by yunkot** [comment]
The issue is: when build completes, CodeLite does not point to any error or warning message location in the file, despite having errors and warnings, even when "Skip warnings" is not checked. In Build output the last message says:
"=== build completed successfully (0 errors, 0 warnings) ==="

Simpler projects do not seem to exhibit these issues.

**Comment by yunkot** [comment]
@eranif : In your list, the issue is #1 and #3 at the same time. #2 is not a problem - clicking works.

I just wanted to explain that when such issues occur, I'm not getting any relevant "(Build Tab View)" messages. However, for the projects that do not exhibit these problems, I'm getting "(Build Tab View)" prefixed messages in the log when trying to build them. So my guess is that for some reason, the code that prints these log messages doesn't get executed at all, when the problem occurs.

**Comment by eranif** [comment]
The only reason this can happen (0 errors, 0 warnings) is:

- Your project has no active compiler set (but how??)
- The regular expression that matches errors is invalid


Every line being added to the output view, is being parsed so you should go through this code blocks:

```c++
if (!m_activeCompiler || !m_activeCompiler->Matches(line, &line_data->match_pattern)) {
    line_data.reset();
} else {
    switch (line_data->match_pattern.sev) {
    case Compiler::kSevError:
        m_errorCount++;
        break;
    case Compiler::kSevWarning:
        m_warnCount++;
        break;
    default:
        break;
    }
}

if (line_data) {
    // set the line project name
    line_data->toolchain = m_activeCompiler ? m_activeCompiler->GetName() : wxString();
    line_data->project_name = m_currentProject;
    line_data->match_pattern.file_path = MakeAbsolute(line_data->match_pattern.file_path);

    clDEBUG() << "(Build Tab View) Storing line info for line:" << cur_line_number << endl;
    m_lineInfo.insert({ cur_line_number, line_data });
}
```

So, since I can't really reproduce this, please add some debug messages build and try to pin point the issue.

The above code block is here:
https://github.com/eranif/codelite/blob/master/LiteEditor/BuildTabView.cpp#L228

And if there are 0 errors, 0 warnings it means that the jump will never work - since it can't find anything to jump to...
The two issues are related

**Comment by eranif** [comment]
I am also interested in seeing your compiler errors and warnings definition (settings -> build settings -> CLANG -> patterns)

I assumed that your compiler is CLANG from this line in the log file:
```
Active compiler is set to: CLANG
```

**Comment by yunkot** [comment]
Regarding above code block, I'll try to investigate tomorrow, although I'm not much familiar with CodeLite source code.

I haven't modified patterns, I suppose these are set by default:
![Patterns](https://github.com/user-attachments/assets/fe934cd6-1593-4d12-8877-546facadbf17)

However, I found why some projects exhibit the issue while others don't. If I set compiler to "GCC", both problems are gone. So the issue only occurs when "Clang" is used as compiler. Clang version is 18.1.3.

Now, even a simple test project exhibits the issue when I pick "Clang" as the compiler!

**Comment by eranif** [comment]
Could you please post here the file `~/.codelite/config/build_settings.xml` ?
I will load it locally - so it will be easier to understand why it fails for you

**Comment by yunkot** [comment]
I have tried this on a different machine (Arch, Clang 18.1.8) and the problem is easily reproducible. 

The steps are the following:
1. Checkout CodeLite from Github and build it according to instructions.
2. Run CodeLite, scan for compilers.
3. Create new C++ workspace, new C++ project.
4. In the project, select Clang as the compiler.
5. In the project source code, write something to trigger error, e.g. just write letter "a".
6. Select Build.
Expected: CodeLite points to the location of error.
Actual: Nothing happens.

**Comment by yunkot** [comment]
> Could you please post here the file `~/.codelite/config/build_settings.xml` ? I will load it locally - so it will be easier to understand why it fails for you

I have this file from a new installation of CodeLite which reproduces the problem.
[build_settings.zip](https://github.com/user-attachments/files/18267295/build_settings.zip)

**Comment by yunkot** [comment]
I have recorded a video to show the problem:
https://github.com/user-attachments/assets/ac49cb6b-8509-4b24-95fa-0c25a1aae88f

**Comment by eranif** [comment]
Thanks, with the video + the settings you provided, I have a local reproduction.
If I choose "/bin/clang" as the compiler -> it does not work
If I choose "/bin/gcc" as the compiler -> it works

**Comment by eranif** [comment]
Fixed. the culprit was:

clang reports the error message with ANSI codes embedded in the line. This broke the regular expression - so no match was found.

For example, what you saw in the build terminal (or in CodeLite build log) was:


```
/home/user/Documents/Test1/Test1/main.cpp:5:26: error: use of undeclared identifier 'aaaa'
```

But the actual string was:

```
^[[1m/home/eran/Documents/Test1/Test1/main.cpp:5:26: ^[[0m^[[0;1;31merror: ^[[0m^[[1muse of undeclared identifier 'aaaa'^[[0m
```

Which the regex did not match

**Comment by yunkot** [comment]
I'm trying build from revision 2561d8ef7db48b883042f08f984723e1c503b732 and so far haven't experienced these issues, so it looks like fixed. Thanks for the detailed explanation! Was the problem caused by the fix to  #3047? Because it didn't occur in the build from November.

**Comment by eranif** [comment]
The actual fix was this line:

https://github.com/eranif/codelite/commit/3081e8bc906687dff0cf5401a309c6661950d8db#diff-f815b092c779bf97bf7f3e2833a3829275e402113bb5b3a56acbefe1eb3e5533R233

which passes: `modified_line` to `m_activeCompiler->Matches(...)` method instead of `line`. `modified_line` is the same as `line` minus the ANSI codes

**Comment by yunkot** [comment]
Thanks a lot for your patience and effort supporting CodeLite. I've just sent you 100$ worth of donation. Best wishes for 2025!
