### ISSUE TITLE
CScope plugin resets executable path

### ISSUE THREAD

**Issue by upCASE** [eranif/codelite#784]
Hi Eran,

I just noticed that when I change the search scope in the cscope plugin from Workspace to
Active Project and the hit the update button, it keeps telling me:
I can't find 'cscope' anywhere. Please check if it's installed.
Or tell me where it can be found, from the menu: 'Plugins | CScope | Settings'

Setting the path again works fine until I change the scope again.
This is on wxGTK, latest HEAD.

Regards,
  René

**Comment by eranif** [comment]
Fixed

**Comment by upCASE** [comment]
Hi Eran,

using latest HEAD, this issue still stands: After changing the combo box setting, I get the error message above and have to set the cscope path again.

Regards,
 René

**Comment by upCASE** [comment]
Hmmm...
It resets the path from /usr/bin/cscope to the installation path of CL, like /home/rene/bin/codelite/bin/cscope

**Comment by eranif** [comment]
For me, no matter what I do, the settings remains... (Linux Mint 17)
Maybe you have write permission error in your ~/.codelite folder? (just guessing)

**Comment by upCASE** [comment]
Hmm... no, permissions are ok.
Cscope is still managed using the codelite.xml file, right?

I'll try some things and get back to you.

**Comment by upCASE** [comment]
I believe I found the reason for this behaviour:
In cscoretabcpp:199 the method reads
```C++
void CscopeTab::OnChangeSearchScope(wxCommandEvent& e)
{
    CScopeConfData data;
    data.SetScanScope(m_stringManager.GetStringSelection());
    data.SetRebuildDbOption(m_checkBoxUpdateDb->IsChecked());
    data.SetBuildRevertedIndexOption(m_checkBoxRevertedIndex->IsChecked());
    m_mgr->GetConfigTool()->WriteObject(wxT("CscopeSettings"), &data);
}
```
In the constructor of CScopeConfData the default path I see is created, but here it is never updated
to the value I set in the settings dialog. There should be a ReadObject for the settings prior to overwriting the values.

**Comment by eranif** [comment]
Should be fixed now

**Comment by upCASE** [comment]
Looking good!
Thanks! :-)
